### ISSUE TITLE
Overload that returns the index, instead of sub-slices

### ISSUE THREAD

**Issue by Quantumplation** [llogiq/partition#4]
This crate would be perfect, if there was a method that returned the index, instead of sub-slices.

For example:

```rust
let v = [1,2,3,4,5];
let idx = partition_index(&mut v, |x| x%2 == 0);
assert_eq!(v, [2,4,1,3,5]);
assert_eq!(idx, 2);
```

If you also think this would be useful, I'm happy to submit a pull request.

**Comment by llogiq** [comment]
That sounds like a very simple extension, so I'd be open for it.

**Comment by Quantumplation** [comment]
@llogiq do you plan on releasing a new version? :sweat_smile:

**Comment by llogiq** [comment]
I do, but I have to find a few minutes to do this. Hopefully within the week.

**Comment by Quantumplation** [comment]
Awesome! Thanks! (and if you get a notification about a :( react, that was just a misclick lol)

**Comment by llogiq** [comment]
Just published to crates.io. Sorry it took me so long, but I bruised a few ribs in a household accident this week, and am on painkillers right now...
